version: '3.8'

services:
  web:
    image: php:7.4-fpm
    volumes:
      - ./www:/var/www/html
    networks:
      - webnet
    depends_on:
      - db
    command: 
      - /bin/sh
      - -c
      - |
          docker-php-ext-install mysqli 
          echo "extension installed.....starting php-fpm........................................"
          php-fpm

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet
    depends_on:
      - web

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    secrets:
      - mysql_root_password
      - mysql_user_password
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports:
      - "8081:80"
    depends_on:
      - db
    secrets:
      - mysql_root_password
    networks:
      - webnet

volumes:
  db_data:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt

networks:
  webnet:

